app:
  name: mucha-frontend
  image:
  port: 3000
  host:

deployment:
  environment: staging
  version:
  strategy: blue-green
  activeColor: blue
  replicas: 2
  canaryEnabled: true
  canaryWeights:
    blue: 90
    green: 10
